dist: trusty # needed for php 5.5

language: php

php:
  - 7.2
  - 5.5

env:
  - TEST_SUITE=tests

matrix:
  fast_finish: true
  allow_failures:
    - php: 5.5

install:
  - composer install

script:
  - vendor/bin/phpunit --debug --verbose --configuration phpunit.xml --testsuite "$TEST_SUITE"
