language: php

php:
  - 5.5
  - 7.2

matrix:
  include:
    - name: "Tests"
      env: TEST_SUITE=tests
  fast_finish: true
  allow_failures:
    - php: 7.2

install:
  - composer install

script:
  - vendor/bin/phpunit --debug --verbose --configuration phpunit.xml --testsuite "$TEST_SUITE"

