language: php

matrix:
  include:
    - name: "Tests php5.5"
      php: "5.5"
      env: TEST_SUITE=tests
    - name: "Tests php 7.2"
      php: "7.2"
      env: TEST_SUITE=tests

install:
  - composer install

script:
  - vendor/bin/phpunit --debug --verbose --configuration phpunit.xml --testsuite "$TEST_SUITE"

